### ISSUE TITLE
Not able make inference from pretrained model

### ISSUE THREAD

**Issue by sumit-chaudhary-pb15** [Sindhu-Hegde/gestsync#1]
Have completed the steps mentioned in the repo, however, not able to make inference, facing issue as below: 

(p38venv_shorts) sumitc@DataPoc1:~/shorts_videos/gestsync$ python inference_activespeaker.py --checkpoint_path=checkpoints/model_rgb.pth --video_path=samples/asd_sample_1.mp4 --global_speaker=True
Traceback (most recent call last):
  File "inference_activespeaker.py", line 20, in <module>
    from protobuf_to_dict import protobuf_to_dict
  File "/home/sumitc@viacom18.com/shorts_videos/p38venv_shorts/lib/python3.8/site-packages/protobuf_to_dict.py", line 15, in <module>
    FieldDescriptor.TYPE_INT64: long,
NameError: name 'long' is not defined

**Comment by Sindhu-Hegde** [comment]
This is an installation issue. Can you try changing the protobuf_to_dict version and check? Also, please ensure that all the libraries installed are of the exact version as listed in the `requirements.txt` file.
